version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8000:8000"
    container_name: FastAPI-container

networks:
  app-network:
    driver: bridge
